# Generated by Django 5.0.4 on 2024-05-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_media_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
