# Generated by Django 5.0.4 on 2024-06-12 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_revealed_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='revealed_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='revealed_contacts',
            field=models.ManyToManyField(blank=True, related_name='revealed_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
