# Generated by Django 5.0.4 on 2024-06-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='plan_id',
            field=models.CharField(choices=[('free', 'Free'), ('plan_OKY2KAyIniksj7', 'Silver'), ('plan_OKY2n03khLtGXm', 'Gold'), ('plan_OKY3XCRSbnODw7', 'Platinum')], default='free', max_length=120),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
