# Generated by Django 5.0.4 on 2024-06-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingprofile_plan_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='plan_id',
            new_name='plan',
        ),
    ]
