# Generated by Django 5.0.4 on 2024-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_plan_id_billingprofile_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='subscription_id',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='subscription_status',
            field=models.CharField(default='', max_length=120),
        ),
    ]
