# Generated by Django 5.0.4 on 2024-05-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_customuser_interests_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
    ]
