# Generated by Django 5.0.4 on 2024-06-12 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='revealed_contacts',
            field=models.ManyToManyField(blank=True, related_name='revealed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
